name = "aigap"
main = "index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[routes]]
pattern = "mcp.aigap.no"
custom_domain = true

[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "AigapMCP" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AigapMCP"]